# Generated by Django 6.0.6 on 2026-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('store_type', models.CharField(choices=[('clothes', 'پوشاک'), ('electronics', 'لوازم الکترونیکی'), ('home', 'لوازم خانگی'), ('food', 'مواد غذایی'), ('other', 'سایر')], max_length=50)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
