# Generated by Django 6.0.6 on 2026-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('clothes', 'لباس'), ('electronics', 'لوازم الکترونیکی'), ('home', 'لوازم خانگی'), ('food', 'مواد غذایی'), ('other', 'سایر')], max_length=50),
        ),
    ]
